version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
        - "8000:8000" # Expose PHP-FPM port internally
    volumes:
      - .:/var/www
    networks: 
      - appnet    

networks:
  appnet:
    driver: bridge
